'Simulation module for Sesipy.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from .worlds.utils import (
        Obstacle,
    )
    from .worlds.world_builder import (
        World,
        WorldBuilder,
        WorldDescriptor,
        Wall,
        Rectangle,
    )
    from .worlds.worlds import (
        Indoor,
        Outdoor,
    )

__all__ = [
    'World',
    'WorldBuilder',
    'WorldDescriptor',
    'Indoor',
    'Outdoor',
    'Obstacle',
    'Wall',
    'Rectangle',
]

_MODULES = {
    'World': '.worlds.world_builder',
    'WorldBuilder': '.worlds.world_builder',
    'WorldDescriptor': '.worlds.world_builder',
    'Indoor': '.worlds.worlds',
    'Outdoor': '.worlds.worlds',
    'Obstacle': '.worlds.utils',
    'Wall': '.worlds.world_builder',
    'Rectangle': '.worlds.world_builder',
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
