repos:
  - repo: local
    hooks:
      - id: generate-package-exports
        name: Update lazy package exports
        entry: python scripts/generate_inits.py
        language: system
        pass_filenames: false
        exclude: ^sesipy/notebooks/
