'Simulator module for Sesipy simulations.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    pass

__all__ = [
]

_MODULES = {
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
