'World building module for Sesipy simulations.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from .utils import (
        Obstacle,
        create_box_mesh,
        create_grid_box_mesh,
        create_grid_plane_mesh,
        create_plane_mesh,
        plane_parameters,
        rotation_matrix_z,
    )
    from .world_builder import (
        Rectangle,
        Wall,
        World,
        WorldBuilder,
        WorldDescriptor,
    )
    from .worlds import (
        Indoor,
        Outdoor,
    )

__all__ = [
    'Indoor',
    'Obstacle',
    'Outdoor',
    'Rectangle',
    'Wall',
    'World',
    'WorldBuilder',
    'WorldDescriptor',
    'create_box_mesh',
    'create_grid_box_mesh',
    'create_grid_plane_mesh',
    'create_plane_mesh',
    'plane_parameters',
    'rotation_matrix_z',
]

_MODULES = {
    'Indoor': '.worlds',
    'Obstacle': '.utils',
    'Outdoor': '.worlds',
    'Rectangle': '.world_builder',
    'Wall': '.world_builder',
    'World': '.world_builder',
    'WorldBuilder': '.world_builder',
    'WorldDescriptor': '.world_builder',
    'create_box_mesh': '.utils',
    'create_grid_box_mesh': '.utils',
    'create_grid_plane_mesh': '.utils',
    'create_plane_mesh': '.utils',
    'plane_parameters': '.utils',
    'rotation_matrix_z': '.utils',
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
