'Sesipy - Spatial Electromagnetic Simulation in Python.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from .data_storage.database import (
        DatabaseReader,
        Database,
        DatabasePS,
        DatabaseAoA,
        encode,
        decode,
    )
    from .engines.evaluation.localization import (
        scoring_surface,
        sample_surface,
    )
    from .engines.evaluation.signals import (
        neighborhood_adjusted_correlation,
        normalize_metrics,
        compare_power_distributions,
        rank_power_distributions,
    )
    from .engines.mapping.environment import (
        Environment,
        Sampler2D,
        Sampler3D,
    )
    from .engines.mapping.utils import (
        map_yaml_to_polygon,
        simulate_lidar,
        cluster_pointcloud,
        remove_small_holes,
        remove_boundary_points,
        extract_lidar_metadata,
        mesh_error,
    )
    from .engines.spatial_intelligence.angle_of_arrival import (
        AoA,
        extract_aoa,
        aoa_projection_2D,
        multi_aoa_projection_2D,
    )
    from .engines.spatial_intelligence.antennas import (
        ReceiverArray,
        TransmitterArray,
        PointSource,
        IsotropicReceiver,
    )
    from .engines.spatial_intelligence.scene import (
        Scene,
    )
    from .engines.spatial_intelligence.utils import (
        scattering_power,
        to_dBm,
        smooth_point_data,
        threshold_point_data,
        create_mesh_copies,
    )
    from .plotting.plot2D import (
        Plot2D,
        mpl_use_latex,
        mpl_font_size,
        mpl_use_seaborn,
        mpl_use_cmap,
    )
    from .plotting.plot3D import (
        Plot3D,
    )
    from .simulation.worlds.utils import (
        Obstacle,
    )
    from .simulation.worlds.world_builder import (
        World,
        WorldBuilder,
        WorldDescriptor,
        Wall,
        Rectangle,
    )
    from .simulation.worlds.worlds import (
        Indoor,
        Outdoor,
    )
    from .utils.array_factory import (
        ArrayFactory,
    )
    from .utils.formatting import (
        Symbols,
        suppress_c_output,
    )
    from .utils.normal_factory import (
        NormalFactory,
    )

__all__ = [
    'ArrayFactory',
    'NormalFactory',
    'Symbols',
    'suppress_c_output',
    'DatabaseReader',
    'Database',
    'DatabasePS',
    'DatabaseAoA',
    'encode',
    'decode',
    'World',
    'Indoor',
    'Outdoor',
    'Obstacle',
    'WorldBuilder',
    'WorldDescriptor',
    'Wall',
    'Rectangle',
    'Plot2D',
    'Plot3D',
    'mpl_use_latex',
    'mpl_font_size',
    'mpl_use_seaborn',
    'mpl_use_cmap',
    'ReceiverArray',
    'TransmitterArray',
    'PointSource',
    'IsotropicReceiver',
    'Scene',
    'scattering_power',
    'to_dBm',
    'smooth_point_data',
    'threshold_point_data',
    'create_mesh_copies',
    'Environment',
    'Sampler2D',
    'Sampler3D',
    'AoA',
    'extract_aoa',
    'aoa_projection_2D',
    'multi_aoa_projection_2D',
    'map_yaml_to_polygon',
    'simulate_lidar',
    'cluster_pointcloud',
    'remove_small_holes',
    'remove_boundary_points',
    'extract_lidar_metadata',
    'mesh_error',
    'scoring_surface',
    'sample_surface',
    'neighborhood_adjusted_correlation',
    'normalize_metrics',
    'compare_power_distributions',
    'rank_power_distributions',
]

_MODULES = {
    'ArrayFactory': '.utils.array_factory',
    'NormalFactory': '.utils.normal_factory',
    'Symbols': '.utils.formatting',
    'suppress_c_output': '.utils.formatting',
    'DatabaseReader': '.data_storage.database',
    'Database': '.data_storage.database',
    'DatabasePS': '.data_storage.database',
    'DatabaseAoA': '.data_storage.database',
    'encode': '.data_storage.database',
    'decode': '.data_storage.database',
    'World': '.simulation.worlds.world_builder',
    'Indoor': '.simulation.worlds.worlds',
    'Outdoor': '.simulation.worlds.worlds',
    'Obstacle': '.simulation.worlds.utils',
    'WorldBuilder': '.simulation.worlds.world_builder',
    'WorldDescriptor': '.simulation.worlds.world_builder',
    'Wall': '.simulation.worlds.world_builder',
    'Rectangle': '.simulation.worlds.world_builder',
    'Plot2D': '.plotting.plot2D',
    'Plot3D': '.plotting.plot3D',
    'mpl_use_latex': '.plotting.plot2D',
    'mpl_font_size': '.plotting.plot2D',
    'mpl_use_seaborn': '.plotting.plot2D',
    'mpl_use_cmap': '.plotting.plot2D',
    'ReceiverArray': '.engines.spatial_intelligence.antennas',
    'TransmitterArray': '.engines.spatial_intelligence.antennas',
    'PointSource': '.engines.spatial_intelligence.antennas',
    'IsotropicReceiver': '.engines.spatial_intelligence.antennas',
    'Scene': '.engines.spatial_intelligence.scene',
    'scattering_power': '.engines.spatial_intelligence.utils',
    'to_dBm': '.engines.spatial_intelligence.utils',
    'smooth_point_data': '.engines.spatial_intelligence.utils',
    'threshold_point_data': '.engines.spatial_intelligence.utils',
    'create_mesh_copies': '.engines.spatial_intelligence.utils',
    'Environment': '.engines.mapping.environment',
    'Sampler2D': '.engines.mapping.environment',
    'Sampler3D': '.engines.mapping.environment',
    'AoA': '.engines.spatial_intelligence.angle_of_arrival',
    'extract_aoa': '.engines.spatial_intelligence.angle_of_arrival',
    'aoa_projection_2D': '.engines.spatial_intelligence.angle_of_arrival',
    'multi_aoa_projection_2D': '.engines.spatial_intelligence.angle_of_arrival',
    'map_yaml_to_polygon': '.engines.mapping.utils',
    'simulate_lidar': '.engines.mapping.utils',
    'cluster_pointcloud': '.engines.mapping.utils',
    'remove_small_holes': '.engines.mapping.utils',
    'remove_boundary_points': '.engines.mapping.utils',
    'extract_lidar_metadata': '.engines.mapping.utils',
    'mesh_error': '.engines.mapping.utils',
    'scoring_surface': '.engines.evaluation.localization',
    'sample_surface': '.engines.evaluation.localization',
    'neighborhood_adjusted_correlation': '.engines.evaluation.signals',
    'normalize_metrics': '.engines.evaluation.signals',
    'compare_power_distributions': '.engines.evaluation.signals',
    'rank_power_distributions': '.engines.evaluation.signals',
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
