'Utility functions and classes for Sesipy.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from .array_factory import (
        ArrayFactory,
    )
    from .formatting import (
        Symbols,
        suppress_c_output,
    )
    from .normal_factory import (
        NormalFactory,
    )

__all__ = [
    'ArrayFactory',
    'NormalFactory',
    'Symbols',
    'suppress_c_output',
]

_MODULES = {
    'ArrayFactory': '.array_factory',
    'NormalFactory': '.normal_factory',
    'Symbols': '.formatting',
    'suppress_c_output': '.formatting',
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
