floor: true
roof: false
walls: true
boundary_z: 5.0
bound:
  xmin: -20.0
  xmax: 20.0
  ymin: -15.0
  ymax: 15.0
generator:
  type: "fixed"
  fixed_obstacles:
    - [-9.75, 12.5, 2.5, 0.5, 5.0, 5.0, 0.0]
    - [-9.75, 5.0, 2.5, 0.5, 4.0, 5.0, 0.0]
    - [-9.75, -2.5, 2.5, 0.5, 5.0, 5.0, 0.0]
    - [-15, -2.5, 2.5, 10.0, 0.5, 5.0, 0.0]
    - [9.75, 11.5, 2.5, 0.5, 7.0, 5.0, 0.0]
    - [16.5, 3.0, 2.5, 7.0, 0.5, 5.0, 0.0]
    - [16.5, -5.0, 2.5, 7.0, 0.5, 5.0, 0.0]
    - [11.42, -6.69, 2.5, 5.0, 0.5, 5.0, 45.0]
    - [-2.0, -10.0, 1.0, 4.0, 3.0, 2.0, 0.0]
    - [2.0, 11.0, 1.0, 3.0, 3.0, 2.0, 45.0]
  random_obstacles:
    small: 0
    medium: 0
    large: 0
    ranges:
      small : [0, 0]
      medium: [0, 0]
      large: [0, 0]