'Mapping module for spatial engines.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from .environment import (
        Environment,
        Sampler2D,
        Sampler3D,
    )
    from .utils import (
        cluster_pointcloud,
        extract_lidar_metadata,
        map_yaml_to_polygon,
        mesh_error,
        remove_boundary_points,
        remove_small_holes,
        simulate_lidar,
    )

__all__ = [
    'Environment',
    'Sampler2D',
    'Sampler3D',
    'cluster_pointcloud',
    'extract_lidar_metadata',
    'map_yaml_to_polygon',
    'mesh_error',
    'remove_boundary_points',
    'remove_small_holes',
    'simulate_lidar',
]

_MODULES = {
    'Environment': '.environment',
    'Sampler2D': '.environment',
    'Sampler3D': '.environment',
    'cluster_pointcloud': '.utils',
    'extract_lidar_metadata': '.utils',
    'map_yaml_to_polygon': '.utils',
    'mesh_error': '.utils',
    'remove_boundary_points': '.utils',
    'remove_small_holes': '.utils',
    'simulate_lidar': '.utils',
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
