'Spatial intelligence engine for electromagnetic simulations.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from .angle_of_arrival import (
        AoA,
        aoa_projection_2D,
        extract_aoa,
        multi_aoa_projection_2D,
    )
    from .antennas import (
        IsotropicReceiver,
        PointSource,
        ReceiverArray,
        TransmitterArray,
    )
    from .scene import (
        Scene,
    )
    from .utils import (
        create_mesh_copies,
        scattering_power,
        smooth_point_data,
        threshold_point_data,
        to_dBm,
    )

__all__ = [
    'AoA',
    'IsotropicReceiver',
    'PointSource',
    'ReceiverArray',
    'Scene',
    'TransmitterArray',
    'aoa_projection_2D',
    'create_mesh_copies',
    'extract_aoa',
    'multi_aoa_projection_2D',
    'scattering_power',
    'smooth_point_data',
    'threshold_point_data',
    'to_dBm',
]

_MODULES = {
    'AoA': '.angle_of_arrival',
    'IsotropicReceiver': '.antennas',
    'PointSource': '.antennas',
    'ReceiverArray': '.antennas',
    'Scene': '.scene',
    'TransmitterArray': '.antennas',
    'aoa_projection_2D': '.angle_of_arrival',
    'create_mesh_copies': '.utils',
    'extract_aoa': '.angle_of_arrival',
    'multi_aoa_projection_2D': '.angle_of_arrival',
    'scattering_power': '.utils',
    'smooth_point_data': '.utils',
    'threshold_point_data': '.utils',
    'to_dBm': '.utils',
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
