"""Generate lazy package exports from literal module __all__ lists, without imports."""

import argparse
import ast
import json
import keyword
from pathlib import Path
import sys


class ExportError(ValueError):
    """Invalid or ambiguous public API declaration."""


def names_list(value, location):
    if not isinstance(value, (list, tuple)) or any(
        not isinstance(name, str) or not name.isidentifier()
        or keyword.iskeyword(name) or name.startswith('_') for name in value
    ):
        raise ExportError(f'{location}: expected a literal list of public Python names')
    if len(value) != len(set(value)):
        raise ExportError(f'{location}: duplicate export names')
    return list(value)


def module_exports(path):
    tree = ast.parse(path.read_text(encoding='utf-8'), filename=str(path))
    declarations = []
    bindings = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            bindings.add(node.name)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            bindings.update(alias.asname or alias.name.split('.')[0] for alias in node.names)
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            stored = {n.id for target in targets for n in ast.walk(target)
                      if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Store)}
            bindings.update(stored)
            if '__all__' in stored:
                declarations.append(node.value)
    if len(declarations) != 1:
        raise ExportError(f'{path}: declare exactly one literal __all__ list (use [] for internal modules)')
    try:
        value = ast.literal_eval(declarations[0])
    except (ValueError, TypeError):
        raise ExportError(f'{path}: __all__ must be a literal list, not computed') from None
    names = names_list(value, path)
    missing = set(names) - bindings
    if missing:
        raise ExportError(f'{path}: exports not defined at module level: {sorted(missing)}')
    # Do not silently accept __all__.append(), +=, or conditional reassignment.
    references = [n for n in ast.walk(tree) if isinstance(n, ast.Name) and n.id == '__all__']
    if len(references) != 1:
        raise ExportError(f'{path}: __all__ must not be modified or computed dynamically')
    return names


def render(package, exports, docstring):
    lines = [repr(docstring), '', '# Generated by scripts/generate_inits.py; do not edit.',
             'from importlib import import_module as _import_module',
             'from typing import TYPE_CHECKING as _TYPE_CHECKING', '', 'if _TYPE_CHECKING:']
    grouped = {}
    for name, module in exports.items():
        relative = '.' + module[len(package) + 1:]
        grouped.setdefault(relative, []).append(name)
    if not grouped:
        lines.append('    pass')
    for module, names in sorted(grouped.items()):
        lines.append(f'    from {module} import (')
        lines.extend(f'        {name},' for name in names)
        lines.append('    )')
    lines.extend(['', '__all__ = ['])
    lines.extend(f'    {name!r},' for name in exports)
    lines.extend([']', '', '_MODULES = {'])
    lines.extend(f'    {name!r}: {("." + module[len(package) + 1:])!r},'
                 for name, module in exports.items())
    lines.extend(['}', '', '', 'def __getattr__(name):',
                  '    module_name = _MODULES.get(name)',
                  '    if module_name is not None:',
                  '        value = getattr(_import_module(module_name, __name__), name)',
                  '        globals()[name] = value',
                  '        return value',
                  '    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")',
                  '', '', 'def __dir__():', '    return __all__[:]', ''])
    return '\n'.join(lines)


def generate(root):
    """Validate the whole tree before returning any proposed file contents."""
    package_root = root / 'sesipy'
    if not package_root.is_dir():
        raise ExportError(f'{root}: missing sesipy directory')
    config = json.loads((root / 'api_exports.json').read_text(encoding='utf-8'))
    if not isinstance(config, dict) or set(config) != {'packages'} or not isinstance(config['packages'], dict):
        raise ExportError('api_exports.json must contain a packages object')
    selections = {name: names_list(names, f'api_exports.json: {name}')
                  for name, names in config['packages'].items()}
    # Notebooks are exploratory code, not modules in the generated public API.
    notebooks = package_root / 'notebooks'
    paths = sorted(
        p for p in package_root.rglob('*.py')
        if '__pycache__' not in p.parts and notebooks not in p.parents
    )
    packages = {package_root}
    for path in paths:
        packages.update(parent for parent in path.parents
                        if parent == package_root or package_root in parent.parents)
    package_names = {'.'.join(path.relative_to(root).parts): path for path in packages}
    unknown = set(selections) - set(package_names)
    if unknown:
        raise ExportError(f'api_exports.json: unknown packages: {sorted(unknown)}')
    modules = {}
    for path in paths:
        if path.name != '__init__.py':
            module = '.'.join(path.relative_to(root).with_suffix('').parts)
            if any(not part.isidentifier() or keyword.iskeyword(part) for part in module.split('.')):
                raise ExportError(f'{path}: invalid Python module name')
            modules[module] = module_exports(path)
    resolved = {}
    output = {}
    for package, directory in sorted(package_names.items(), key=lambda item: (-item[0].count('.'), item[0])):
        candidates = {}
        def add(name, module):
            if name in candidates and candidates[name] != module:
                raise ExportError(f'{package}: duplicate export {name!r} from {candidates[name]} and {module}')
            candidates[name] = module
        children = set()
        for module, names in modules.items():
            if module.rpartition('.')[0] == package:
                children.add(module.rpartition('.')[2])
                for name in names:
                    add(name, module)
        for child, names in resolved.items():
            if child.rpartition('.')[0] == package:
                children.add(child.rpartition('.')[2])
                for name, module in names.items():
                    add(name, module)
        chosen = selections.get(package, sorted(candidates))
        missing = set(chosen) - set(candidates)
        if missing:
            raise ExportError(f'{package}: selected names no longer exported: {sorted(missing)}')
        collisions = set(chosen) & children
        if collisions:
            raise ExportError(f'{package}: exports collide with submodule names: {sorted(collisions)}')
        resolved[package] = {name: candidates[name] for name in chosen}
        init = directory / '__init__.py'
        doc = ast.get_docstring(ast.parse(init.read_text(encoding='utf-8'))) if init.exists() else None
        output[init] = render(package, resolved[package], doc or f'Public API for {package}.')
    return output


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Report stale files without writing; exit 1 if any differ')
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1], help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        output = generate(root)
    except (ExportError, OSError, SyntaxError, json.JSONDecodeError) as exc:
        parser.exit(2, f'Export generation failed: {exc}\n')
    changed = [path for path, content in output.items()
               if not path.exists() or path.read_text(encoding='utf-8') != content]
    for path in sorted(changed):
        if not args.check:
            path.write_text(output[path], encoding='utf-8')
        print(f'{"Stale" if args.check else "Updated"}: {path.relative_to(root)}')
    if not changed:
        print('All package initializers are up to date.')
    if args.check and changed:
        print('Run python scripts/generate_inits.py and commit the updated files.')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
