'Engines module for Sesipy.'

# Generated by scripts/generate_inits.py; do not edit.
from importlib import import_module as _import_module
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from .evaluation.localization import (
        sample_surface,
        scoring_surface,
    )
    from .evaluation.signals import (
        compare_power_distributions,
        neighborhood_adjusted_correlation,
        normalize_metrics,
        rank_power_distributions,
    )
    from .mapping.environment import (
        Environment,
        Sampler2D,
        Sampler3D,
    )
    from .mapping.utils import (
        cluster_pointcloud,
        extract_lidar_metadata,
        map_yaml_to_polygon,
        mesh_error,
        remove_boundary_points,
        remove_small_holes,
        simulate_lidar,
    )
    from .spatial_intelligence.angle_of_arrival import (
        AoA,
        aoa_projection_2D,
        extract_aoa,
        multi_aoa_projection_2D,
    )
    from .spatial_intelligence.antennas import (
        IsotropicReceiver,
        PointSource,
        ReceiverArray,
        TransmitterArray,
    )
    from .spatial_intelligence.scene import (
        Scene,
    )
    from .spatial_intelligence.utils import (
        create_mesh_copies,
        scattering_power,
        smooth_point_data,
        threshold_point_data,
        to_dBm,
    )

__all__ = [
    'AoA',
    'Environment',
    'IsotropicReceiver',
    'PointSource',
    'ReceiverArray',
    'Sampler2D',
    'Sampler3D',
    'Scene',
    'TransmitterArray',
    'aoa_projection_2D',
    'cluster_pointcloud',
    'compare_power_distributions',
    'create_mesh_copies',
    'extract_aoa',
    'extract_lidar_metadata',
    'map_yaml_to_polygon',
    'mesh_error',
    'multi_aoa_projection_2D',
    'neighborhood_adjusted_correlation',
    'normalize_metrics',
    'rank_power_distributions',
    'remove_boundary_points',
    'remove_small_holes',
    'sample_surface',
    'scattering_power',
    'scoring_surface',
    'simulate_lidar',
    'smooth_point_data',
    'threshold_point_data',
    'to_dBm',
]

_MODULES = {
    'AoA': '.spatial_intelligence.angle_of_arrival',
    'Environment': '.mapping.environment',
    'IsotropicReceiver': '.spatial_intelligence.antennas',
    'PointSource': '.spatial_intelligence.antennas',
    'ReceiverArray': '.spatial_intelligence.antennas',
    'Sampler2D': '.mapping.environment',
    'Sampler3D': '.mapping.environment',
    'Scene': '.spatial_intelligence.scene',
    'TransmitterArray': '.spatial_intelligence.antennas',
    'aoa_projection_2D': '.spatial_intelligence.angle_of_arrival',
    'cluster_pointcloud': '.mapping.utils',
    'compare_power_distributions': '.evaluation.signals',
    'create_mesh_copies': '.spatial_intelligence.utils',
    'extract_aoa': '.spatial_intelligence.angle_of_arrival',
    'extract_lidar_metadata': '.mapping.utils',
    'map_yaml_to_polygon': '.mapping.utils',
    'mesh_error': '.mapping.utils',
    'multi_aoa_projection_2D': '.spatial_intelligence.angle_of_arrival',
    'neighborhood_adjusted_correlation': '.evaluation.signals',
    'normalize_metrics': '.evaluation.signals',
    'rank_power_distributions': '.evaluation.signals',
    'remove_boundary_points': '.mapping.utils',
    'remove_small_holes': '.mapping.utils',
    'sample_surface': '.evaluation.localization',
    'scattering_power': '.spatial_intelligence.utils',
    'scoring_surface': '.evaluation.localization',
    'simulate_lidar': '.mapping.utils',
    'smooth_point_data': '.spatial_intelligence.utils',
    'threshold_point_data': '.spatial_intelligence.utils',
    'to_dBm': '.spatial_intelligence.utils',
}


def __getattr__(name):
    module_name = _MODULES.get(name)
    if module_name is not None:
        value = getattr(_import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return __all__[:]
